### ISSUE TITLE
Some DICOM IS values still not parsed as integers

### ISSUE THREAD

**Issue by bersbersbers** [exiftool/exiftool#12]
The fix for #10 is almost complete, seemingly parsing all-digit strings as integers now that trailing spaces are removed. However, the example data from #9 (http://medistim.com/wp-content/uploads/2016/07/ttfm.dcm) still has another edge case: `"NumberOfFrames" => " 1",`

This value is represented the same way by `dcmdump`:
`(0028,0008) IS [ 1]                                     #   2, 1 NumberOfFrames`

Note that this is perfectly OK with the DICOM standard:
> IS: A string of characters representing an Integer in base-10 (decimal), shall contain only the characters 0 - 9, with an optional leading "+" or "-". It **may be padded with leading** and/or trailing **spaces**. Embedded spaces are not allowed.

My interpretation is that `" 1"` should be converted to integer `1`, too. I am not sure whether all leading spaces should be removed from all strings: one could for value representations such as IS or CS ("A string of characters with leading or trailing spaces (20H) being non-significant."), but one cannot for others such as ST ("It may be padded with trailing spaces, which may be ignored, but leading spaces are considered to be significant.").

http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

Does exiftool have a dictionary of value representations for all tags?

**Comment by boardhead** [comment]
Yes, ExifTool has a value representation for all tags.

Let me see if this is what you want:

1. Trim leading and trailing spaces from IS, AE, CS, DS, PN and SH.

2. Trim trailing spaces from LT, ST and UT.

**Comment by bersbersbers** [comment]
Yes, that is largely my understanding. Some additions:

1. I would also trim leading and trailing spaces from LO, but I am not fully certain this is allowed.

2. You should also trim trailing spaces from DT and TM (they are not allowed anywhere in the value, so they must be insignificant; one might safely trim from the beginning for the same reason).

**Comment by boardhead** [comment]
Thanks.  I'll add LO.  I was already parsing DA/TM/DT to effectively remove trailing spaces, but I'll patch to also ignore leading spaces.

**Comment by boardhead** [comment]
This should be fixed in version 11.30 (just released).

**Comment by bersbersbers** [comment]
I am still seeing this:

```
> wget http://medistim.com/wp-content/uploads/2016/07/ttfm.dcm
> exiftool -ver
11.30
>exiftool -php ttfm.dcm | grep NumberOfFrames
  "NumberOfFrames" => " 1",
```

Shouldn't the leading space in `NumberOfFrames` be gone and `"1"` be parsed as `1`?

**Comment by boardhead** [comment]
Yes.  You are right.  Thanks for checking up on this.  I obviously didn't test this very well... try again in 11.31.

**Comment by boardhead** [comment]
Version 11.31 is now available (11539794a481685c5ba12ecf25fbe3c1d2eaa2a3), but I won't close this issue until I have confirmation that it works.

**Comment by bersbersbers** [comment]
Looks good to me!

**Comment by boardhead** [comment]
Great!
